// ============================================================
// DONNEES PRODUITS — La Cave des Senteurs
// ============================================================

const WHATSAPP_NUMBER = "22898879988";

const PRODUCTS = [
  // ── PARFUMS ──────────────────────────────────────────────
  {
    id: 1,
    nom: "Sakura",
    marque: "Christian Dior",
    categorie: "parfums",
    prix: 45000,
    devise: "FCFA",
    description: "Un voyage olfactif au coeur du Japon. Sakura de Christian Dior capture la delicatesse de la fleur de cerisier, melee a la douceur de la rose et du musc. Une fragrance florale et poudree, legere comme un souffle de printemps.",
    notes: { tete: "Fleur de cerisier, Notes vertes", coeur: "Rose, Mimosa, Violette", fond: "Musc" },
    longevite: "6 heures",
    sillage: "Modere",
    genre: "Pour homme et femme",
    volume: "125 ml",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/sakura.jpg"],
    emoji: "&#127800;"
  },
  {
    id: 2,
    nom: "Good Girl Gone Bad",
    marque: "By Kilian",
    categorie: "parfums",
    prix: 52000,
    devise: "FCFA",
    description: "Good Girl Gone Bad de By Kilian est une fragrance florale et fruitee pour femme. Un bouquet envoûtant d'osmanthus, tuberose et jasmin, avec une touche d'ambre. Sensuelle, audacieuse et inoubliable.",
    notes: { tete: "Osmanthus, Tuberose", coeur: "Jasmin, Narcisse, Rose", fond: "Ambre" },
    longevite: "7 heures",
    sillage: "Fort",
    genre: "Pour femme",
    volume: "50 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: true,
    images: ["img/gone-girl-2026.jpeg"],
    emoji: "&#127801;"
  },
  {
    id: 3,
    nom: "Imagination",
    marque: "Louis Vuitton",
    categorie: "parfums",
    prix: 45000,
    devise: "FCFA",
    description: "Imagination de Louis Vuitton est une fragrance fraiche et agrumee pour homme. Un melange enivrant de the, cedrat et bergamote, rehausse de neroli et d'ambroxan. Elegance et modernite reunies.",
    notes: { tete: "The, Cedrat, Bergamote", coeur: "Orange, Neroli", fond: "Ambroxan, Ambre" },
    longevite: "7 heures",
    sillage: "Fort",
    genre: "Pour homme",
    volume: "100 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: false,
    images: ["img/imagination-new.jpeg"],
    emoji: "&#128167;"
  },
  {
    id: 4,
    nom: "Tobacco Honey",
    marque: "Guerlain",
    categorie: "parfums",
    prix: 45000,
    devise: "FCFA",
    description: "Tobacco Honey de Guerlain est une fragrance orientale gourmande. Un accord envoûtant de miel, tabac et vanille, rehausse de feve de tonka et d'oud. Chaleureux, enveloppant et profondement sensuel.",
    notes: { tete: "Miel, Tabac", coeur: "Vanille, Feve de tonka", fond: "Clou de girofle, Oud" },
    longevite: "8 heures",
    sillage: "Fort",
    genre: "Pour homme et femme",
    volume: "200 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: true,
    images: ["img/tabaco-new.jpeg"],
    emoji: "&#127855;"
  },
  {
    id: 5,
    nom: "Irresistible Rose Velvet",
    marque: "Givenchy",
    categorie: "parfums",
    prix: 40000,
    devise: "FCFA",
    description: "Irresistible Rose Velvet de Givenchy est une eau de parfum florale et veloutee pour femme. La rose se pare d'une intensite nouvelle, profonde et sensuelle. Un sillage envoûtant qui allie douceur et caractere.",
    notes: { tete: "Rose, Bergamote", coeur: "Rose veloutee, Pivoine", fond: "Musc blanc, Bois de santal" },
    longevite: "7 heures",
    sillage: "Modere",
    genre: "Pour femme",
    volume: "50 ml",
    nouveaute: true,
    bestSeller: false,
    stockLimite: true,
    images: ["img/parfums.jpeg"],
    emoji: "&#127801;"
  },
  {
    id: 6,
    nom: "Ultra Male",
    marque: "Jean Paul Gaultier",
    categorie: "parfums",
    prix: 46600,
    devise: "FCFA",
    description: "Ultra Male de Jean Paul Gaultier est une fragrance orientale et gourmande pour homme. Une version plus intense et seduisante du celebre Le Male. Notes de poire, lavande et vanille pour un homme audacieux et magnetique.",
    notes: { tete: "Poire, Bergamote", coeur: "Lavande, Iris", fond: "Vanille, Ambre, Musc" },
    longevite: "8 heures",
    sillage: "Fort",
    genre: "Pour homme",
    volume: "125 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: false,
    images: ["img/ultra-male.jpeg"],
    emoji: "&#128171;"
  },

  // ── DIFFUSEURS ────────────────────────────────────────────
  {
    id: 7,
    nom: "Diffuseur Loris Mangue",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 8500,
    devise: "FCFA",
    description: "Diffuseur a roseaux Loris aux notes fruitees et gourmandes de mangue. Un parfum tropical et ensolleille qui transforme votre interieur en un veritable paradis olfactif.",
    volume: "Grand format",
    duree: "4 a 6 semaines",
    nouveaute: true,
    images: ["img/diffiseures.jpeg"],
    emoji: "&#127818;"
  },
  {
    id: 8,
    nom: "Diffuseur Loris Fruits",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 8500,
    devise: "FCFA",
    description: "Diffuseur a roseaux Loris aux notes fruitees et florales. Un melange frais et sucre qui parfume delicatement chaque piece de votre maison avec elegance.",
    volume: "Grand format",
    duree: "4 a 6 semaines",
    nouveaute: true,
    images: ["img/diffisueres5.jpeg"],
    emoji: "&#127815;"
  },
  {
    id: 9,
    nom: "Diffuseur Loris Fleurs Blanches",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 8500,
    devise: "FCFA",
    description: "Diffuseur a roseaux Loris aux notes florales blanches et poudrees. La purete des fleurs blanches capturee dans un diffuseur elegant pour un interieur toujours parfume.",
    volume: "Grand format",
    duree: "4 a 6 semaines",
    nouveaute: false,
    images: ["img/div1.jpeg"],
    emoji: "&#129716;"
  },
  {
    id: 10,
    nom: "Diffuseur Loris Mini",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 5500,
    devise: "FCFA",
    description: "Diffuseur a roseaux Loris format mini, ideal pour les petits espaces. Parfumez votre bureau, salle de bain ou entree avec cette fragrance delicate et persistante.",
    volume: "Petit format",
    duree: "2 a 3 semaines",
    nouveaute: false,
    images: ["img/div2.jpeg"],
    emoji: "&#127807;"
  },

  // ── HUILES PARFUMEES ──────────────────────────────────────
  {
    id: 11,
    nom: "Huile Parfumee Gloria",
    marque: "Gloria Perfume",
    categorie: "huiles-parfumees",
    prix: 8500,
    devise: "FCFA",
    description: "Huile parfumee Gloria Perfume en flacon roll-on de 10ml. Une fragrance concentree et longue tenue pour parfumer votre peau toute la journee. Pratique et elegante.",
    volume: "10 ml",
    utilisation: "Corps, poignets, cou",
    nouveaute: true,
    images: ["img/huile1.png"],
    emoji: "&#127801;"
  },
  {
    id: 12,
    nom: "Huile Parfumee Gloria Noire",
    marque: "Gloria Perfume",
    categorie: "huiles-parfumees",
    prix: 8500,
    devise: "FCFA",
    description: "Huile parfumee Gloria Perfume edition noire en flacon roll-on de 10ml. Une fragrance orientale intense et envoûtante. Quelques gouttes suffisent pour un sillage remarquable.",
    volume: "10 ml",
    utilisation: "Corps, poignets, cou",
    nouveaute: true,
    images: ["img/huile2.png"],
    emoji: "&#10024;"
  },
  {
    id: 13,
    nom: "Huile Parfumee Gloria Rouge",
    marque: "Gloria Perfume",
    categorie: "huiles-parfumees",
    prix: 8500,
    devise: "FCFA",
    description: "Huile parfumee Gloria Perfume edition rouge en flacon roll-on de 10ml. Une fragrance florale et fruitee, douce et feminine. Parfaite pour un usage quotidien.",
    volume: "10 ml",
    utilisation: "Corps, poignets, cou",
    nouveaute: false,
    images: ["img/huile.jpeg"],
    emoji: "&#128705;"
  },
  {
    id: 14,
    nom: "Huile Parfumee Gloria Or",
    marque: "Gloria Perfume",
    categorie: "huiles-parfumees",
    prix: 8500,
    devise: "FCFA",
    description: "Huile parfumee Gloria Perfume edition or en flacon roll-on de 10ml. Une fragrance precieuse et luxueuse aux notes orientales. Un tresor olfactif a porter sur soi.",
    volume: "10 ml",
    utilisation: "Corps, poignets, cou",
    nouveaute: true,
    images: ["img/Gloria.jpeg"],
    emoji: "&#127818;"
  },
  // ── NOUVEAUX PARFUMS ─────────────────────────────────────
  {
    id: 15,
    nom: "Hibiscus MahaJad",
    marque: "Maison Crivelli",
    categorie: "parfums",
    prix: 0,
    devise: "FCFA",
    description: "Hibiscus MahaJad de Maison Crivelli est un extrait de parfum d'une intensite rare. L'hibiscus rouge eclate comme une fleur tropicale en plein soleil, marie a des notes de fruits rouges juteux et d'une base boisee et musquee. Une fragrance vivante, solaire et profondement envoûtante.",
    notes: { tete: "Hibiscus, Fruits rouges", coeur: "Rose, Jasmin", fond: "Musc, Bois de santal" },
    longevite: "8 heures",
    sillage: "Fort",
    genre: "Pour homme et femme",
    volume: "50 ml",
    nouveaute: true,
    bestSeller: false,
    stockLimite: true,
    images: ["img/hibiscus-mahajad.jpeg"],
    emoji: "🌺"
  },
  {
    id: 16,
    nom: "La Vie est Belle L'Extrait",
    marque: "Lancome",
    categorie: "parfums",
    prix: 0,
    devise: "FCFA",
    description: "La Vie est Belle L'Extrait de Lancome est la version la plus intense et la plus luxueuse de l'iconique La Vie est Belle. Un bouquet de praline rose, iris et jasmin sambac d'une richesse incomparable. Sensuel, gourmand et inoubliable — une declaration d'amour a la vie.",
    notes: { tete: "Praline rose, Bergamote", coeur: "Iris, Jasmin sambac, Rose", fond: "Praline, Vanille, Patchouli" },
    longevite: "10 heures",
    sillage: "Fort",
    genre: "Pour femme",
    volume: "50 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: false,
    images: ["img/la-vie-est-belle.jpeg"],
    emoji: "&#10024;"
  },
  {
    id: 17,
    nom: "Tuxedo Sharp Patchouli",
    marque: "Yves Saint Laurent",
    categorie: "parfums",
    prix: 0,
    devise: "FCFA",
    description: "Tuxedo Sharp Patchouli de Yves Saint Laurent est une fragrance boisee et aromatique d'une elegance absolue. Le patchouli tranchant s'allie a des notes de cuir, d'epices et de bois precieux pour creer un sillage masculin et sophistique. Pour l'homme qui ose.",
    notes: { tete: "Epices, Bergamote", coeur: "Patchouli, Cuir", fond: "Bois de santal, Vetiver, Ambre" },
    longevite: "9 heures",
    sillage: "Fort",
    genre: "Pour homme",
    volume: "100 ml",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/tuxedo-ysl.jpeg"],
    emoji: "&#128171;"
  },

  // ── NOUVEAUX DIFFUSEURS ───────────────────────────────────
  {
    id: 18,
    nom: "Diffuseur Loris Rose",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 6500,
    devise: "FCFA",
    description: "Diffuseur a roseaux Loris senteur Rose. Un bouquet floral delicat et romantique qui enveloppe votre interieur d'une douceur petale. Ideal pour creer une atmosphere elegante et apaisante.",
    notes: { tete: "Rose fraiche", coeur: "Rose centifolia", fond: "Musc blanc, Bois de santal" },
    volume: "120 ml",
    duree: "3 a 5 semaines",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/loris-rose.jpeg"],
    emoji: "&#127801;"
  },
  {
    id: 19,
    nom: "Diffuseur Loris Peche",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 4500,
    devise: "FCFA",
    description: "Diffuseur a roseaux Loris senteur Peche. Une fragrance fruitee et juteuse qui rappelle les vergers en ete. Douce, gourmande et ensoleillee, elle parfume votre interieur avec une chaleur naturelle.",
    notes: { tete: "Peche juteuse", coeur: "Fleur de pecher", fond: "Vanille, Musc" },
    volume: "100 ml",
    duree: "3 a 4 semaines",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/loris-peche.jpeg"],
    emoji: "&#127825;"
  },
  {
    id: 20,
    nom: "Diffuseur de Voiture Melon",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 1700,
    devise: "FCFA",
    description: "Diffuseur de voiture Loris senteur Melon. Une fragrance fruitee et rafraichissante pour transformer votre habitacle en oasis de fraicheur. Compact, efficace et longue duree.",
    volume: "10 ml",
    duree: "2 a 3 semaines",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/voiture-melon.jpeg"],
    emoji: "&#127820;"
  },
  {
    id: 21,
    nom: "Diffuseur de Voiture Mangue",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 1700,
    devise: "FCFA",
    description: "Diffuseur de voiture Loris senteur Mangue. Un parfum tropical et ensoleille pour vos trajets quotidiens. La mangue juteuse et exotique transforme chaque trajet en voyage sensoriel.",
    volume: "10 ml",
    duree: "2 a 3 semaines",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/voiture-mangue.jpeg"],
    emoji: "&#127818;"
  },
  {
    id: 22,
    nom: "Diffuseur de Voiture Peche",
    marque: "Loris",
    categorie: "diffuseurs",
    prix: 1700,
    devise: "FCFA",
    description: "Diffuseur de voiture Loris senteur Peche. Une fragrance douce et fruitee pour parfumer votre voiture avec elegance. La peche veloutee apporte une touche gourmande et apaisante a vos trajets.",
    volume: "10 ml",
    duree: "2 a 3 semaines",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/voiture-peche.jpeg"],
    emoji: "&#127825;"
  },

  // ── SPRAYS D'INTERIEUR ────────────────────────────────────
  {
    id: 23,
    nom: "Room Spray Patchouli-Bergamote",
    marque: "Maison",
    categorie: "sprays",
    prix: 5500,
    devise: "FCFA",
    description: "Room spray senteur Patchouli-Bergamote. Un accord boise et agrume qui purifie et parfume instantanement votre espace. Le patchouli terreux se marie a la bergamote vive pour une atmosphere unique et sophistiquee.",
    notes: { tete: "Bergamote, Citron", coeur: "Patchouli, Vetiver", fond: "Musc, Bois de cedre" },
    volume: "500 ml",
    utilisation: "Chambre, salon, bureau",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/spray-patchouli.jpeg"],
    emoji: "&#127807;"
  },
  {
    id: 24,
    nom: "Diffuseur Era Fleur de Cerisier",
    marque: "Era by Gandour",
    categorie: "diffuseurs",
    prix: 3000,
    devise: "FCFA",
    description: "Diffuseur Era by Gandour senteur Fleur de Cerisier. Un voyage olfactif au coeur du Japon avec cette fragrance florale delicate et poudree. La fleur de cerisier capture la beaute ephemere du printemps.",
    notes: { tete: "Fleur de cerisier, Notes vertes", coeur: "Rose, Pivoine", fond: "Musc blanc, Bois de santal" },
    volume: "30 ml",
    duree: "2 a 3 semaines",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/era-cerisier.jpeg"],
    emoji: "&#127800;"
  },
  {
    id: 25,
    nom: "Spray Interieur Era Melon",
    marque: "Era by Gandour",
    categorie: "sprays",
    prix: 3000,
    devise: "FCFA",
    description: "Spray d'interieur Era by Gandour senteur Melon. Une fragrance fruitee et rafraichissante qui transforme instantanement l'atmosphere de votre piece. Legere et estivale, elle apporte une touche de fraicheur naturelle.",
    notes: { tete: "Melon frais, Concombre", coeur: "Fleurs blanches", fond: "Musc, Ambre blanc" },
    volume: "400 ml",
    utilisation: "Chambre, salon, salle de bain",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/era-melon.jpeg"],
    emoji: "&#127820;"
  },
  {
    id: 26,
    nom: "Spray Interieur Era Fleur de Cerisier",
    marque: "Era by Gandour",
    categorie: "sprays",
    prix: 3000,
    devise: "FCFA",
    description: "Spray d'interieur Era by Gandour senteur Fleur de Cerisier. La delicatesse de la fleur de cerisier en spray pour parfumer instantanement votre interieur. Une fragrance florale et poudree d'une elegance japonaise.",
    notes: { tete: "Fleur de cerisier", coeur: "Rose, Jasmin", fond: "Musc blanc, Vanille" },
    volume: "400 ml",
    utilisation: "Chambre, salon, salle de bain",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/era-spray-cerisier.jpeg"],
    emoji: "&#127800;"
  },
  {
    id: 27,
    nom: "Era Car Fruits Rouges",
    marque: "Era by Gandour",
    categorie: "diffuseurs",
    prix: 1500,
    devise: "FCFA",
    description: "Diffuseur de voiture Era by Gandour senteur Fruits Rouges. Un melange gourmand et vitamine de fraise, framboise et cerise pour parfumer votre habitacle avec energie et bonne humeur.",
    notes: { tete: "Fraise, Framboise", coeur: "Cerise, Groseille", fond: "Musc, Vanille" },
    volume: "10 ml",
    duree: "2 a 3 semaines",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/era-car-fruits.jpeg"],
    emoji: "&#127815;"
  },
  {
    id: 28,
    nom: "Spray Interieur Era Grenade",
    marque: "Era by Gandour",
    categorie: "sprays",
    prix: 3000,
    devise: "FCFA",
    description: "Spray d'interieur Era by Gandour senteur Grenade. Une fragrance fruitee et acidulee aux notes de grenade juteuse. Vivifiante et originale, elle apporte une touche exotique et rafraichissante a votre interieur.",
    notes: { tete: "Grenade, Fruits rouges", coeur: "Rose, Pivoine", fond: "Musc, Ambre" },
    volume: "400 ml",
    utilisation: "Chambre, salon, salle de bain",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/era-grenade.jpeg"],
    emoji: "&#127815;"
  },
  {
    id: 29,
    nom: "Spray Interieur Era Barbe a Papa",
    marque: "Era by Gandour",
    categorie: "sprays",
    prix: 3000,
    devise: "FCFA",
    description: "Spray d'interieur Era by Gandour senteur Barbe a Papa. Une fragrance gourmande et sucree qui rappelle les fetes foraines et les douceurs de l'enfance. Joyeuse, enveloppante et inoubliable.",
    notes: { tete: "Sucre, Fraise", coeur: "Vanille, Caramel", fond: "Musc doux, Ambre" },
    volume: "400 ml",
    utilisation: "Chambre, salon, salle de bain",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/era-barbe-papa.jpeg"],
    emoji: "&#127852;"
  },
  {
    id: 30,
    nom: "Spray Interieur Era Mangue-Framboises",
    marque: "Era by Gandour",
    categorie: "sprays",
    prix: 3000,
    devise: "FCFA",
    description: "Spray d'interieur Era by Gandour senteur Mangue-Framboises. Un duo fruité tropical et acidule qui illumine instantanement votre espace. La mangue exotique et la framboise vive forment un accord frais et vitamine.",
    notes: { tete: "Mangue, Framboise", coeur: "Fruits tropicaux, Fleurs blanches", fond: "Musc, Vanille" },
    volume: "400 ml",
    utilisation: "Chambre, salon, salle de bain",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/era-mangue-framboise.jpeg"],
    emoji: "&#127818;"
  },
  {
    id: 31,
    nom: "Spray Interieur Era Fraicheur d'Agrumes",
    marque: "Era by Gandour",
    categorie: "sprays",
    prix: 3000,
    devise: "FCFA",
    description: "Spray d'interieur Era by Gandour senteur Fraicheur d'Agrumes. Un bouquet d'agrumes vifs et toniques — citron, orange et pamplemousse — pour purifier et revitaliser votre interieur. Frais, propre et energisant.",
    notes: { tete: "Citron, Pamplemousse, Orange", coeur: "Bergamote, Neroli", fond: "Musc blanc, Bois leger" },
    volume: "400 ml",
    utilisation: "Chambre, salon, bureau",
    nouveaute: true,
    bestSeller: false,
    stockLimite: false,
    images: ["img/era-agrumes.jpeg"],
    emoji: "&#127819;"
  },
  {
    id: 32,
    nom: "Trio Era Diffuseur",
    marque: "Era by Gandour",
    categorie: "diffuseurs",
    prix: 8500,
    devise: "FCFA",
    description: "Coffret Trio Era by Gandour — 3 diffuseurs de 30ml chacun. Un assortiment de senteurs pour varier les plaisirs olfactifs selon vos envies et les pieces de votre maison. Le cadeau ideal pour les amateurs de parfums d'ambiance.",
    volume: "3 x 30 ml",
    duree: "2 a 3 semaines par diffuseur",
    nouveaute: true,
    bestSeller: true,
    stockLimite: true,
    images: ["img/era-trio.jpeg"],
    emoji: "&#127807;"
  },

  // ── NOUVEAUX PARFUMS DE LUXE ──────────────────────────────
  {
    id: 33,
    nom: "Vanilla Candy Rock Sugar 42",
    marque: "Kayali",
    categorie: "parfums",
    prix: 32500,
    devise: "FCFA",
    description: "Vanilla Candy Rock Sugar 42 de Kayali est une fragrance gourmande et addictive. Un accord de vanille cristalline, sucre de roche et notes fruitees qui evoque les confiseries les plus precieuses. Doux, enveloppant et inoubliable.",
    notes: { tete: "Sucre de roche, Fruits rouges", coeur: "Vanille, Caramel", fond: "Musc blanc, Bois de santal, Ambre" },
    longevite: "8 heures",
    sillage: "Fort",
    genre: "Pour femme",
    volume: "100 ml",
    nouveaute: true,
    bestSeller: false,
    stockLimite: true,
    images: ["img/kayali-vanilla-candy.jpeg"],
    emoji: "&#127852;"
  },
  {
    id: 34,
    nom: "Vanilla 28",
    marque: "Kayali",
    categorie: "parfums",
    prix: 40000,
    devise: "FCFA",
    description: "Vanilla 28 de Kayali est une ode a la vanille dans toute sa splendeur. Une fragrance orientale et gourmande d'une richesse incomparable — vanille de Madagascar, feve de tonka et musc chaud. Sensuelle, profonde et envoûtante.",
    notes: { tete: "Vanille de Madagascar, Bergamote", coeur: "Feve de tonka, Praline", fond: "Musc chaud, Bois de santal, Ambre" },
    longevite: "10 heures",
    sillage: "Fort",
    genre: "Pour femme",
    volume: "50 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: false,
    images: ["img/kayali-vanilla-28.jpeg"],
    emoji: "&#127855;"
  },
  {
    id: 35,
    nom: "Kirke",
    marque: "Tiziana Terenzi",
    categorie: "parfums",
    prix: 50000,
    devise: "FCFA",
    description: "Kirke de Tiziana Terenzi est un extrait de parfum d'une complexite rare. Inspire de la magicienne grecque Circe, cette fragrance fruitee et boisee melange peche, jasmin et bois de santal dans un accord envoûtant et mysterieux. Un chef-d'oeuvre olfactif.",
    notes: { tete: "Peche, Bergamote, Citron", coeur: "Jasmin, Rose, Ylang-ylang", fond: "Bois de santal, Musc, Ambre, Vanille" },
    longevite: "12 heures",
    sillage: "Fort",
    genre: "Pour homme et femme",
    volume: "50 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: true,
    images: ["img/kirke-tiziana.jpeg"],
    emoji: "&#10024;"
  },
  {
    id: 36,
    nom: "Miss Dior",
    marque: "Christian Dior",
    categorie: "parfums",
    prix: 35500,
    devise: "FCFA",
    description: "Miss Dior de Christian Dior est une eau de parfum florale et chypree d'une feminite absolue. La pivoine fraiche et la rose de Grasse s'unissent dans un accord delicat et moderne. L'icone de la parfumerie feminine revisitee avec elegance.",
    notes: { tete: "Bergamote, Mandarine", coeur: "Pivoine, Rose de Grasse", fond: "Patchouli, Musc blanc, Bois de santal" },
    longevite: "7 heures",
    sillage: "Modere",
    genre: "Pour femme",
    volume: "80 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: false,
    images: ["img/miss-dior.jpeg"],
    emoji: "&#127801;"
  },
  {
    id: 37,
    nom: "Lady Million",
    marque: "Paco Rabanne",
    categorie: "parfums",
    prix: 38500,
    devise: "FCFA",
    description: "Lady Million de Paco Rabanne est une fragrance florale et chypree pour la femme audacieuse. Un accord de jasmin blanc, framboise et miel d'acacia dans un flacon en forme de diamant. Luxueux, seduisant et inoubliable.",
    notes: { tete: "Framboise, Pamplemousse", coeur: "Jasmin blanc, Fleur d'oranger", fond: "Miel d'acacia, Patchouli, Bois de santal" },
    longevite: "8 heures",
    sillage: "Fort",
    genre: "Pour femme",
    volume: "80 ml",
    nouveaute: true,
    bestSeller: true,
    stockLimite: false,
    images: ["img/lady-million.jpeg"],
    emoji: "&#128142;"
  },
  {
    id: 38,
    nom: "Oud Satin Mood",
    marque: "Maison Francis Kurkdjian",
    categorie: "parfums",
    prix: 52000,
    devise: "FCFA",
    description: "Oud Satin Mood de Maison Francis Kurkdjian est une fragrance orientale d'une opulence rare. L'oud precieux se marie a la rose de Damas et a la vanille dans un accord soyeux et envoûtant. Coffret de 5 flacons de 11ml avec camouflage de bouteille — le luxe absolu.",
    notes: { tete: "Rose de Damas, Bergamote", coeur: "Oud, Encens", fond: "Vanille, Musc, Ambre" },
    longevite: "12 heures",
    sillage: "Fort",
    genre: "Pour homme et femme",
    volume: "11 ml x 5",
    nouveaute: true,
    bestSeller: true,
    stockLimite: true,
    images: ["img/oud-satin-mood.jpeg"],
    emoji: "&#128142;"
  }
];

// Lien WhatsApp avec message pre-rempli
function getWhatsAppLink(produit) {
  const devise = produit.devise || "FCFA";
  const prixText = produit.prix > 0
    ? "Prix : " + produit.prix.toLocaleString() + " " + devise + "\n"
    : "Prix : A confirmer\n";
  const msg = encodeURIComponent(
    "Bonjour, je souhaite commander :\n\n" +
    "Produit : *" + produit.nom + "*\n" +
    (produit.marque ? "Marque : " + produit.marque + "\n" : "") +
    prixText +
    (produit.volume ? "Volume : " + produit.volume + "\n" : "") +
    "\nMerci de me confirmer la disponibilite."
  );
  return "https://wa.me/" + WHATSAPP_NUMBER + "?text=" + msg;
}

function getCategorieLabel(cat) {
  const labels = {
    "parfums": "Parfums",
    "diffuseurs": "Diffuseurs",
    "huiles-parfumees": "Huiles Parfumees",
    "sprays": "Sprays d'Interieur"
  };
  return labels[cat] || cat;
}

function getPrixRange(produit) {
  if (produit.prix === 0)        return "sur-demande";  // Prix sur demande
  if (produit.prix <= 5000)      return "moins-5k";     // Moins de 5 000
  if (produit.prix <= 10000)     return "5k-10k";       // 5 000 – 10 000
  if (produit.prix <= 35000)     return "10k-35k";      // 10 000 – 35 000
  if (produit.prix <= 50000)     return "35k-50k";      // 35 000 – 50 000
  return "plus-50k";                                    // Plus de 50 000
}
